import { useQuery } from '@tanstack/react-query';
import { Activity, ArrowLeft, Bot, Github } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { api } from '../lib/api';
import { Empty, PageHeader, Skeleton, Status } from '../components/UI';
type Row={id:string;workflow_name:string;status:string;mode:string;started_at:string;duration_ms:number|null;trigger_json:string};
export function Executions(){const query=useQuery({queryKey:['executions'],queryFn:()=>api<Row[]>('/api/executions')});return <div className="page"><PageHeader eyebrow="OBSERVABILITY" title="Executions" description="Inspect every trigger, decision, action, and retry."/><section className="panel executions-panel"><header><h2>All runs</h2><div className="filter-tabs"><button className="active">All</button><button>Success</button><button>Failed</button><button>Test</button></div></header>{query.isLoading?<Skeleton rows={5}/>:query.data?.length?<div className="execution-table"><div className="table-head"><span>Workflow</span><span>Status</span><span>Mode</span><span>Started</span><span>Duration</span></div>{query.data.map((row)=><Link to={`/executions/${row.id}`} key={row.id}><span><i className="event-icon"><Github size={15}/></i><b>{row.workflow_name}</b></span><Status value={row.status}/><small>{row.mode}</small><time>{new Date(row.started_at).toLocaleString()}</time><code>{row.duration_ms?`${row.duration_ms} ms`:'—'}</code></Link>)}</div>:<Empty icon={<Activity/>} title="No executions yet" body="Test or activate a workflow to see its complete execution trace here."/>}</section></div>}
type Detail={execution:Record<string,string|number|null>;nodes:Array<Record<string,string|number|null>>;aiUsage:Array<Record<string,string|number|null>>};
export function ExecutionDetail(){const {id}=useParams();const query=useQuery({queryKey:['execution',id],queryFn:()=>api<Detail>(`/api/executions/${id}`)});if(query.isLoading)return <div className="page"><Skeleton rows={5}/></div>;if(!query.data)return null;const {execution,nodes,aiUsage}=query.data;return <div className="page"><Link className="back" to="/executions"><ArrowLeft size={14}/>Executions</Link><PageHeader eyebrow={`EXECUTION · ${execution.mode}`} title={String(execution.workflow_name)} description={`Started ${new Date(String(execution.started_at)).toLocaleString()}`} action={<Status value={String(execution.status)}/>}/><div className="detail-grid"><section className="panel timeline"><header><h2>Execution timeline</h2><code>{String(execution.id)}</code></header>{nodes.map((node,index)=><article key={String(node.id)}><span className="timeline-line">{index<nodes.length-1&&<i/>}<b>{index+1}</b></span><div><header><b>{String(node.node_id)}</b><Status value={String(node.status)}/><time>{node.duration_ms} ms</time></header>{node.error&&<p className="error-text">{String(node.error)}</p>}<details><summary>Inspect input and output</summary><div className="json-grid"><pre>{formatJson(node.input_json)}</pre><pre>{formatJson(node.output_json)}</pre></div></details></div></article>)}</section><aside><section className="panel run-summary"><h2>Run summary</h2><dl><dt>Status</dt><dd><Status value={String(execution.status)}/></dd><dt>Duration</dt><dd>{execution.duration_ms} ms</dd><dt>Version</dt><dd>v{execution.workflow_version}</dd><dt>Mode</dt><dd>{String(execution.mode)}</dd></dl></section><section className="panel ai-card"><header><Bot size={17}/><h2>AI usage</h2></header>{aiUsage.length?aiUsage.map((usage)=><dl key={String(usage.id)}><dt>Provider</dt><dd>{String(usage.provider)}</dd><dt>Model</dt><dd>{String(usage.model)}</dd><dt>Tokens</dt><dd>{Number(usage.input_tokens)+Number(usage.output_tokens)}</dd><dt>Latency</dt><dd>{usage.duration_ms} ms</dd></dl>):<p>No AI nodes ran.</p>}</section></aside></div></div>}
function formatJson(value:string|number|null|undefined){if(!value)return 'No data';try{return JSON.stringify(JSON.parse(String(value)),null,2)}catch{return String(value)}}
