import { useMutation, useQuery } from '@tanstack/react-query';
import { ArrowUpRight, Github, Globe2, Mail, Webhook } from 'lucide-react';
import { api } from '../lib/api';
import { PageHeader, Status } from '../components/UI';
import { useEffect, useRef, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
type GitHubData={configured:boolean;appSlug:string|null;installations:Array<Record<string,string|number>>};
export function Integrations(){const github=useQuery({queryKey:['github-integration'],queryFn:()=>api<GitHubData>('/api/integrations/github')});const connect=useMutation({mutationFn:()=>api<{url:string}>('/api/integrations/github/connect',{method:'POST'}),onSuccess:({url})=>location.assign(url)});const cards=[{Icon:Github,name:'GitHub',copy:'Trigger workflows and act on pull requests and issues.',status:github.data?.installations.length?'Connected':'Not connected',action:<button className="button" disabled={!github.data?.configured} onClick={()=>connect.mutate()}>{github.data?.installations.length?'Manage repositories':'Connect'}<ArrowUpRight size={14}/></button>},{Icon:Mail,name:'Email',copy:'Send transactional alerts through Resend or local log mode.',status:'Available',action:<span className="provider-label">RESEND</span>},{Icon:Webhook,name:'Webhooks',copy:'Receive events from any service with optional secret auth.',status:'Available',action:<span className="provider-label">NATIVE</span>},{Icon:Globe2,name:'HTTP',copy:'Call external HTTPS APIs with safe timeouts and redacted logs.',status:'Available',action:<span className="provider-label">NATIVE</span>}];return <div className="page"><PageHeader eyebrow="CONNECTIONS" title="Integrations" description="Connect event sources and action providers to Trigg."/><div className="integration-grid">{cards.map(({Icon,name,copy,status,action})=><article className="integration-card" key={name}><header><span><Icon/></span><Status value={status}/></header><h2>{name}</h2><p>{copy}</p><footer>{action}</footer></article>)}</div><section className="coming"><h2>Coming next</h2><p>These are roadmap integrations, not simulated connections.</p><div>{['Slack','Discord','Linear','Notion','Jira'].map((name)=><span key={name}><i>{name[0]}</i>{name}<small>COMING SOON</small></span>)}</div></section></div>}

export function GitHubCallback(){const [params]=useSearchParams();const [message,setMessage]=useState('Syncing repositories from your GitHub App installation…');const started=useRef(false);useEffect(()=>{const installationId=params.get('installation_id');if(!installationId||started.current){if(!installationId)setMessage('GitHub did not return an installation ID.');return;}started.current=true;void api<{repositories:number}>('/api/integrations/github/callback',{method:'POST',body:JSON.stringify({installationId})}).then(({repositories})=>setMessage(`Connected. ${repositories} repositories are ready.`)).catch((error:unknown)=>setMessage(error instanceof Error?error.message:'Could not connect GitHub.'));},[params]);return <div className="page"><PageHeader eyebrow="GITHUB APP" title="Finishing connection" description={message}/><Link className="button primary" to="/integrations">Back to integrations</Link></div>}
