import { useMutation, useQuery } from '@tanstack/react-query';
import { ArrowUpRight, Github } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { api } from '../lib/api';
import { PageHeader, Status } from '../components/UI';
type GitHubInstallation=Record<string,string|number>&{missingPermissions?:string[]};
type GitHubData={configured:boolean;appSlug:string|null;installations:GitHubInstallation[]};
export function Integrations(){const github=useQuery({queryKey:['github-integration'],queryFn:()=>api<GitHubData>('/api/integrations/github'),retry:false});const connect=useMutation({mutationFn:()=>api<{url:string}>('/api/integrations/github/connect',{method:'POST'}),onSuccess:({url})=>location.assign(url)});const connected=Boolean(github.data?.installations.length);const failure=github.error??connect.error;const retry=()=>void github.refetch();const incomplete=(github.data?.installations??[]).filter((installation)=>installation.missingPermissions?.length);return <div className="page"><PageHeader eyebrow="CONNECTIONS" title="GitHub" description="Connect repositories that Trigg should review."/>{incomplete.map((installation)=><div className="notice" key={String(installation.installation_id)}><strong>{String(installation.account_login)} is missing permissions.</strong> Trigg cannot post reviews or checks until {installation.missingPermissions?.join(' and ')} {(installation.missingPermissions?.length??0)>1?'are':'is'} accepted. Granting a permission on the app only requests it; each installation has to accept it. <a href={`https://github.com/settings/installations/${String(installation.installation_id)}/permissions/update`} target="_blank" rel="noreferrer">Review the request on GitHub</a>.</div>)}<div className="integration-grid"><article className="integration-card"><header><span><Github/></span><Status value={failure?'Error':connected?'Connected':'Not connected'}/></header><h2>GitHub App</h2><p>Listen for pull requests, fetch their code changes, and post Trigg reviews.</p>{failure&&<small>{failure instanceof Error?failure.message:'Could not load the GitHub integration.'}</small>} {!failure&&github.data&&!github.data.configured&&<small>The GitHub App is not configured on the backend.</small>}<footer><button className="button" disabled={github.isLoading||connect.isPending||Boolean(github.data&&!github.data.configured)} onClick={failure?retry:()=>connect.mutate()}>{failure?'Retry':connected?'Choose repositories':'Connect GitHub'}<ArrowUpRight size={14}/></button></footer></article></div></div>}
export function GitHubCallback(){const [params]=useSearchParams();const [message,setMessage]=useState('Syncing repositories from your GitHub App installation…');const started=useRef(false);useEffect(()=>{const installationId=params.get('installation_id');const state=params.get('state');if(!installationId||!state||started.current){if(!installationId||!state)setMessage('GitHub did not return a valid installation response.');return;}started.current=true;void api<{repositories:number}>('/api/integrations/github/callback',{method:'POST',body:JSON.stringify({installationId,state})}).then(({repositories})=>setMessage(`Connected. ${repositories} repositories are ready.`)).catch((error:unknown)=>setMessage(error instanceof Error?error.message:'Could not connect GitHub.'));},[params]);return <div className="page"><PageHeader eyebrow="GITHUB APP" title="Finishing connection" description={message}/><Link className="button primary" to="/workflows">Create a reviewer</Link></div>}
