import { useMutation, useQuery } from '@tanstack/react-query';
import { ArrowUpRight, Github } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { api } from '../lib/api';
import { PageHeader, Status } from '../components/UI';
type GitHubData={configured:boolean;appSlug:string|null;installations:Array<Record<string,string|number>>};
export function Integrations(){const github=useQuery({queryKey:['github-integration'],queryFn:()=>api<GitHubData>('/api/integrations/github')});const connect=useMutation({mutationFn:()=>api<{url:string}>('/api/integrations/github/connect',{method:'POST'}),onSuccess:({url})=>location.assign(url)});const connected=Boolean(github.data?.installations.length);return <div className="page"><PageHeader eyebrow="CONNECTIONS" title="GitHub" description="Connect repositories that Trigg should review."/><div className="integration-grid"><article className="integration-card"><header><span><Github/></span><Status value={connected?'Connected':'Not connected'}/></header><h2>GitHub App</h2><p>Listen for pull requests, fetch their code changes, and post Trigg reviews.</p><footer><button className="button" disabled={!github.data?.configured||connect.isPending} onClick={()=>connect.mutate()}>{connected?'Choose repositories':'Connect GitHub'}<ArrowUpRight size={14}/></button></footer></article></div></div>}
export function GitHubCallback(){const [params]=useSearchParams();const [message,setMessage]=useState('Syncing repositories from your GitHub App installation…');const started=useRef(false);useEffect(()=>{const installationId=params.get('installation_id');const state=params.get('state');if(!installationId||!state||started.current){if(!installationId||!state)setMessage('GitHub did not return a valid installation response.');return;}started.current=true;void api<{repositories:number}>('/api/integrations/github/callback',{method:'POST',body:JSON.stringify({installationId,state})}).then(({repositories})=>setMessage(`Connected. ${repositories} repositories are ready.`)).catch((error:unknown)=>setMessage(error instanceof Error?error.message:'Could not connect GitHub.'));},[params]);return <div className="page"><PageHeader eyebrow="GITHUB APP" title="Finishing connection" description={message}/><Link className="button primary" to="/workflows">Create a reviewer</Link></div>}
